### ISSUE TITLE
Production error: '>' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by BryceStevenWilley** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#433]
There are also some variants that are `'>' not supported between instances of 'NoneType' and 'NoneType'`

```
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8124, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8699, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8486, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9324, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9229, in askfor
    return question.ask(user_dict, old_user_dict, the_x, iterators, missing_var, origMissingVariable)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6400, in ask
    defaults[field.number] = field.default.text(user_dict).strip()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 1582, in text
    return self.template.render(**the_user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 874, in _render
    _render_context(
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 943, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7fc4210b52d0", line 26, in render_body
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/HousingCodeChecklist/load_data.py", line 269, in conditions_days
    return abs( (self.conditions_end(default_date) - self.conditions_start(default_date)).days )
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/HousingCodeChecklist/load_data.py", line 261, in conditions_end
    return max([
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

The external hostname was apps.suffolklitlab.org
```

**Comment by miabonardi** [comment]
Note for Mia: Potentially means one of the rows came back empty, make sure no empty cells in sheet where something should be
